x-app-build: &app-build
  context: .
  dockerfile: Dockerfile
  target: dev

x-mlflow-build: &mlflow-build
  context: .
  dockerfile: Dockerfile
  target: mlflow-runtime

services:
  api:
    build: *app-build
    command:
      - uvicorn
      - src.api:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --log-level
      - ${UVICORN_LOG_LEVEL:-info}
      - --reload
    volumes:
      - ./data:/app/data:ro
      - ./src:/app/src
      - ./trainer.py:/app/trainer.py:ro
      - models:/app/models
      - outputs:/app/outputs
      - mlruns:/app/mlruns

  streamlit:
    build: *app-build
    command:
      - streamlit
      - run
      - app.py
      - --server.address=0.0.0.0
      - --server.port=8501
      - --server.headless=true
      - --server.runOnSave=true
    volumes:
      - ./app.py:/app/app.py
      - ./src:/app/src
      - ./trainer.py:/app/trainer.py:ro
      - ./data:/app/data:ro
      - models:/app/models
      - outputs:/app/outputs
      - mlruns:/app/mlruns

  trainer:
    build: *app-build
    volumes:
      - ./data:/app/data:ro
      - ./src:/app/src
      - ./trainer.py:/app/trainer.py
      - models:/app/models
      - outputs:/app/outputs
      - mlruns:/app/mlruns

  mlflow:
    build: *mlflow-build
