services:
  api:
    command:
      - uvicorn
      - src.api:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --log-level
      - ${UVICORN_LOG_LEVEL:-info}
      - --reload
    volumes:
      - ./src:/app/src

  streamlit:
    command:
      - streamlit
      - run
      - app.py
      - --server.address=0.0.0.0
      - --server.port=8501
      - --server.headless=true
      - --server.runOnSave=true
    volumes:
      - .:/app

  trainer:
    volumes:
      - .:/app
